### ISSUE TITLE
合并未生效

### ISSUE THREAD

**Issue by yhlchao** [Kujiale-Mobile/changeAppJsonPlugin#1]
配置目录：
![image](https://user-images.githubusercontent.com/33980809/91379466-5ab69200-e855-11ea-8e13-24a039d25980.png)

插件源文件（直接复制）：
![image](https://user-images.githubusercontent.com/33980809/91379554-88034000-e855-11ea-817a-a51010ac65f0.png)

config/index.js 配置文件：
![image](https://user-images.githubusercontent.com/33980809/91379795-095ad280-e856-11ea-9659-471f7b904e72.png)

Taro (app.tsx 中的配置)：
pages/training/index 为原生小程序页面
![image](https://user-images.githubusercontent.com/33980809/91379943-58a10300-e856-11ea-849e-d002e7eb8816.png)

打包结果：
![image](https://user-images.githubusercontent.com/33980809/91379994-7b331c00-e856-11ea-8452-03a1826bf2b7.png)

你好，是否可以帮忙看一下呢，感谢~

**Comment by rottenpen** [comment]
output部分代码是写在 app config 里， 不是在 config / index里

**Comment by yhlchao** [comment]
@rottenpen 好的，生效了，感谢~
